### ISSUE TITLE
开箱时箱子图片链接失效

### ISSUE THREAD

**Issue by ABKQPO** [roiiiu/nonebot-plugin-csgo-case-simulator#1]
显示[CQ:image,file=https://steamcdn-a.akamaihd.net/apps/730/icons/econ/weapon_cases/crate_valve_1.23c783d005b446a1004c97057cfb5ac2d8dae186.png,type=,cache=true,proxy=true,timeout=]正在开启反恐精英武器箱...

**Comment by roiiiu** [comment]
> 显示[CQ:image,file=https://steamcdn-a.akamaihd.net/apps/730/icons/econ/weapon_cases/crate_valve_1.23c783d005b446a1004c97057cfb5ac2d8dae186.png,type=,cache=true,proxy=true,timeout=]正在开启反恐精英武器箱...

现在图片都会以base64发送，应该会在新版中得到修复: b57ac17
