### ISSUE TITLE
【功能建议】在使用中的一些小想法

### ISSUE THREAD

**Issue by ab-Royo** [roiiiu/nonebot-plugin-csgo-case-simulator#12]
大佬今天更新的0.1.17已经用上了，目前没有遇到问题，但是有几个地方可以优化一下？
1.  使用指令查看所有纪念包时，连发两个文本消息过长（查看所有武器箱也可以优化优化？）

可以使用合并转发消息来折叠消息，或者是使用 [pil-utils](https://github.com/MeetWq/pil-utils) 来制作成图片

2. 指令可否同时兼容中文指令

使用的其他插件都是中文指令，英文指令有一些不太符合直觉
例如中文指令:
|        指令        | 权限  | 需要@ | 范围  |      说明      |
| :----------------: | :---: | :---: | :---: | :------------: |
| csgo开箱 [数量] [名称] | 群员  |  否   | 群聊  |   开启武器箱   |
|       csgo全部武器箱        | 群员  |  否   | 群聊  | 查看所有武器箱 |
|        csgo全部纪念包         | 群员  |  否   | 群聊  | 查看所有纪念包 |
|      csgo皮肤      | 群员  |  否   | 群聊  |    搜索皮肤    |

3. 在生成的抽卡结果上标注谁抽的，来源箱子和结果信息

比如 `xx 抽取了 xx次 xx箱， 共抽出了 x 个紫， x个蓝，xxx皮肤 抽出了最多x次 `这样子

**Comment by roiiiu** [comment]
> 

根据建议发布了新版，指令别名有部分修改，详见README🥳

**Comment by ab-Royo** [comment]
好耶！大佬早些休息
