### ISSUE TITLE
插件无法触发

### ISSUE THREAD

**Issue by hateStudyy** [roiiiu/nonebot-plugin-csgo-case-simulator#13]
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/115376190/6c25053a-97bd-4611-8873-bfa16ae2deb2)
为什么触发不了奇怪😂
作者帮帮我

**Comment by roiiiu** [comment]
> ![image](https://user-images.githubusercontent.com/115376190/260676410-6c25053a-97bd-4611-8873-bfa16ae2deb2.png) 为什么触发不了奇怪😂 作者帮帮我

加指令前缀 一般是```/```

**Comment by hateStudyy** [comment]
哦哦解决了！忘记这个了哈哈
