### ISSUE TITLE
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2546)

### ISSUE THREAD

**Issue by Lfhsheng** [roiiiu/nonebot-plugin-csgo-case-simulator#14]
如题，我认为是SSL证书问题，完整报错可见[此处](https://paste.ubuntu.com/p/WYXgF4mXZ9/)。

**Comment by roiiiu** [comment]
> 如题，我认为是SSL证书问题，完整报错可见[此处](https://paste.ubuntu.com/p/WYXgF4mXZ9/)。

发布了0.1.20版本，关闭了ssl验证，如果还出现这个问题那就是api仓库的原因了。

**Comment by Lfhsheng** [comment]
感谢大佬修复
