### ISSUE TITLE
插件开箱报错

### ISSUE THREAD

**Issue by FasAway** [roiiiu/nonebot-plugin-csgo-case-simulator#15]
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/73431401/a2d0c3f1-1995-4f7e-a2ed-13332a60b01f)
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/73431401/bf67891d-c48f-4b75-838d-fddfbd6e5906)

**Comment by roiiiu** [comment]
@FasAway 漏打包了资源文件，更新0.2.1版本即可修复。
