### ISSUE TITLE
希望能加个cd，插件太受欢迎一直被人刷

### ISSUE THREAD

**Issue by 360add** [roiiiu/nonebot-plugin-csgo-case-simulator#16]

**Comment by roiiiu** [comment]
@360add 现在可以通过环境变量`CSGO_CD`来设置每个用户的开箱冷却时间，默认是无冷却。
<img width="95" alt="image" src="https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/11494827/a73fa596-42c5-45fd-bb97-17ebd717033e">

**Comment by 360add** [comment]
更新了？

**Comment by 360add** [comment]
感谢

**Comment by 360add** [comment]
太强辣，启动失败的问题也解决了，👍

**Comment by 360add** [comment]
> @360add 现在可以通过环境变量来设置每个用户的开箱冷却时间，默认是无冷却。`CSGO_CD` <img alt="图像" width="95" src="https://user-images.githubusercontent.com/11494827/269004424-a73fa596-42c5-45fd-bb97-17ebd717033e.png">

太强辣，启动失败的问题也解决了，👍
