### ISSUE TITLE
初始化加载json文件冲突

### ISSUE THREAD

**Issue by 360add** [roiiiu/nonebot-plugin-csgo-case-simulator#17]
![QQ截图20230919185636](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/a7d1e22c-fee7-4e78-b1a4-4720de2ea040)

**Comment by roiiiu** [comment]
api源仓库的问题，多试几次就可以了，下个版本我添加一下离线的json文件。@360add

**Comment by 360add** [comment]
![QQ截图20230919185636](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/f2d4a0a4-f741-461d-9ec6-c148fb797760)
试了几次都这样了

**Comment by 360add** [comment]
前面被刷太厉害刷崩了

**Comment by roiiiu** [comment]
> 前面被刷太厉害刷崩了

启动只会获取一次列表文件，开箱过程中图源都来自steam官方，这个是启动报错，不会被刷崩。

**Comment by 360add** [comment]
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/ab3af5af-5555-4543-9b06-8752ffcbf5c5)
发现个事，只要cs开箱插件启动成功了，这个定时任务插件和60s插件就会启动失败
，相反只要定时和60s启动成功，开箱也会启动失败，大佬知道什么原因吗

**Comment by roiiiu** [comment]
> 
> ![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/ab3af5af-5555-4543-9b06-8752ffcbf5c5)
> 发现个事，只要cs开箱插件启动成功了，这个定时任务插件和60s插件就会启动失败
> ，相反只要定时和60s启动成功，开箱也会启动失败，大佬知道什么原因吗

https://github.com/nonebot/plugin-apscheduler/issues/30#issuecomment-1627754868

**Comment by 360add** [comment]
不要在加载插件前import插件模块，大佬这是啥意思，我要去哪里修改，刚才在
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/c573c738-531c-4edf-9fce-999e98d461c5)
这里面改了插件的顺序不知道是不是这个原因，现在启动了一次成功了，不知道算解决了没有，

**Comment by 360add** [comment]
![XEGP}M3 _6(O00V136E3N}S](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/4076ad03-3c0e-458b-a497-20414cfb5ee9)
gang刚问了大佬，有大佬指出这里有问题，
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/38554ac9-c9a7-4279-bf7c-c526055ecf6b)

**Comment by roiiiu** [comment]
> ![XEGP}M3 _6(O00V136E3N}S](https://user-images.githubusercontent.com/140232510/268969697-4076ad03-3c0e-458b-a497-20414cfb5ee9.png) gang刚问了大佬，有大佬指出这里有问题， ![image](https://user-images.githubusercontent.com/140232510/268969903-38554ac9-c9a7-4279-bf7c-c526055ecf6b.png)

需要更深入调查，我会在下个版本中修复。

**Comment by roiiiu** [comment]
请升级到0.2.2版本，问题应该得到修复。
