### ISSUE TITLE
亲爱的作者大大，能否加个群共享cd，现在有了个人cd，但是如果刷的人多了还是容易刷屏，造成账号被风控

### ISSUE THREAD

**Issue by 360add** [roiiiu/nonebot-plugin-csgo-case-simulator#18]
亲爱的作者大大，能否加个群共享cd，现在有了个人cd，但是如果刷的人多了还是容易刷屏，造成账号被风控，所以可以加个群共享cd吗，不是个人而是整个群的cd

**Comment by roiiiu** [comment]
> 亲爱的作者大大，能否加个群共享cd，现在有了个人cd，但是如果刷的人多了还是容易刷屏，造成账号被风控，所以可以加个群共享cd吗，不是个人而是整个群的cd

<img width="167" alt="image" src="https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/11494827/6811d75b-7a64-49b7-8fe0-77df70f219b7">
更新0.2.3版本以使用新功能。

**Comment by 360add** [comment]
大大牛批
![%K7OD)XHUEJWT$C{OG8K4 4](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/adc4cc3c-d186-4226-b8f7-789a4b628c71)
