### ISSUE TITLE
皮肤搜索功能失效

### ISSUE THREAD

**Issue by VAHua** [roiiiu/nonebot-plugin-csgo-case-simulator#20]
试过多种格式，还是不能搜索出皮肤，求大佬指点一下
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/e503613c-fa08-4861-990e-1f7e5b89c538)
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/2b64ca2d-5a02-4dc8-b8d8-dc3161d6b2eb)
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/544588f7-54ab-4945-b280-94e416d8422f)

**Comment by roiiiu** [comment]
`s_skins`不是`s_skin`
<img width="155" alt="image" src="https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/11494827/149776a0-e8a7-4076-a6dc-6c7a7535bbfa">

**Comment by VAHua** [comment]
还是不行呢
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/0fd8cced-0f17-49c8-80cc-587cb6411c2c)
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/36caf9b2-4bcb-4e20-9ede-e69b0a530a06)

**Comment by VAHua** [comment]
求大佬举个例子

**Comment by roiiiu** [comment]
> 还是不行呢 ![image](https://private-user-images.githubusercontent.com/129832780/307743677-0fd8cced-0f17-49c8-80cc-587cb6411c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDE5NjAsIm5iZiI6MTcwODk0MTY2MCwicGF0aCI6Ii8xMjk4MzI3ODAvMzA3NzQzNjc3LTBmZDhjY2VkLTBmMTctNDljOC04MGNjLTU4N2NiNjQxMWMyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMDAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTM3OWE3ZTRjYmJjNDEwNTM1MmZmN2U1NmQ1MjIwYzFjMGFlNzg3MjQ2NDg5YzljZDA5YzczNTM5NTQ1ZmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8CSyysSFwq4xImEp4h87a6DbCHHsPw0zzct-1N6twmI) ![image](https://private-user-images.githubusercontent.com/129832780/307743726-36caf9b2-4bcb-4e20-9ede-e69b0a530a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDE5NjAsIm5iZiI6MTcwODk0MTY2MCwicGF0aCI6Ii8xMjk4MzI3ODAvMzA3NzQzNzI2LTM2Y2FmOWIyLTRiY2ItNGUyMC05ZWRlLWU2OWIwYTUzMGEwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMDAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODlmMjIxZTMyOThhNDhlYTgzMzNkMjMxZDg0ZjVkZWIxNzFiZjZlYjlhNzMxNjU1OTQ3NmNiODM5ZjE2NTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.okjwzA8xIxTJYG7719iW4v1xWixxDPyfAZhlW8wQ7HE)

好像就是s_skin,过去很久我也记不太清了 ,这个功能没作为主要功能,所以随手简单写了一下,你试试搜索皮肤名,不带武器名,比如s_skin 二西莫夫

**Comment by VAHua** [comment]
经过测试，还是不行
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/7b382e55-8df3-4be8-8b54-33088188e456)

**Comment by roiiiu** [comment]
> 经过测试，还是不行
> ![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/129832780/7b382e55-8df3-4be8-8b54-33088188e456)
> 

哦 查出来了是代码的问题json文件格式更新了搜索皮肤的代码没更新。有空我会修一下
