### ISSUE TITLE
纪念包没有金 openuntil会一直进行

### ISSUE THREAD

**Issue by FangChanguwu** [roiiiu/nonebot-plugin-csgo-case-simulator#21]
如题，希望能优化这个问题，顺便催更一下千瓦武器箱)

**Comment by roiiiu** [comment]
> 如题，希望能优化这个问题，顺便催更一下千瓦武器箱)

openuntil是开发调试时用的 没有把它放在正式功能列表里

**Comment by roiiiu** [comment]
> 如题，希望能优化这个问题，顺便催更一下千瓦武器箱)

武器箱已更新
