### ISSUE TITLE
HTTPX版本的问题

### ISSUE THREAD

**Issue by RainbowDashKira** [roiiiu/nonebot-plugin-csgo-case-simulator#6]
因为我在安装了本插件以后，安装其他插件的时候总会提示，其他插件要求的是23，而本插件要求的是24，然后启动机器人的时候插件就加载失败了。本人纯小白，只是机器人换了个电脑重新弄的时候出现这个问题，以前装同样的插件没有这个问题，如果觉得不合适或者是我自己的问题可以close。

**Comment by roiiiu** [comment]
@RainbowDashKira 你好，现在httpx依赖版本已降为^0.23，该问题会在新版本中得到修复。
